<?php

namespace App\Models;

use App\Models\Helpers\CawModel;
use App\Models\Helpers\CawHelpers;
use Illuminate\Http\Request;
use \DB;

class BankAccount extends CawModel
{

    protected $table    =  'bank_account';
    protected $fillable = [
        'name',
        'id_bank',
        'agency',
        'account_current',
        'currentBalance',
        'balance_date',
        'bill_option',
        'wallet',
        'special_code',
        'pact',
        'transmission_code',
        'complement',
        'local_pay',
        'instruction',
        'who_send_ticket',
        'priceOfSend',
        'active',
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];

    public $timestamps = true;

    public static function getList(Request $request){
        $builder = BankAccount::select('bank_account.*','cb_bank.name AS bank_name')
                    ->join('cb_bank','bank_account.id_bank', '=','cb_bank.id');

//        dd($builder);
        CawHelpers::addWhereLike($builder, 'bank_account.name', $request['name']);

        if( $request['active'] != null){
            $builder->where('bank_account.active', '=',  $request['active']);
        }


        $builder->orderBy('bank_account.name');

        return $builder->paginate(config('app.list_count'))->appends($request->except('page'));
    }

    public function save(array $options = [])
    {
        if($this->name == "")
        {
            return new \Exception('O campo nome do serviço é obrigatório.');
        }
        if($this->currentBalance == "" || $this->price == "R$ 0") {
            return new \Exception('O campo saldo inicial é obrigatório.');
        }
        if($this->balance_date == "")
        {
            return new \Exception('O campo data do saldo é obrigatório.');
        }

        return parent::save($options); // TODO: Change the autogenerated stub
    }


    public static function activeDisabled($id, $type){

        try {
            $service = BankAccount::where('id', '=', $id)
                ->first();
            if($service != null) {

                if ($type == 1) {
                    $service->active = 0;
                } else {
                    $service->active = 1;
                }

                $res = $service->save();

                if($res === true){
                    return true;
                }else{
                    return false;
                }
            }else{
                return false;
            }

        }catch (QueryException $e){
            return false;
        }
    }
}