<?php

namespace App\Models;

use App\Models\Helpers\CawModel;
use App\Models\Helpers\CawHelpers;
use Illuminate\Http\Request;
use \DB;
use Mockery\Exception;

class Car extends CawModel
{

    protected $table    =  'car';
    protected $fillable = [
        'id_contract',
        'license_plate',
        'model',
        'color',
        'chassis',
        'driver_license',
        'active',
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];

    public $timestamps = true;

    public static function getList(Request $request){

        $builder = Car::select('car.*');

        CawHelpers::addWhereLike($builder, 'model', $request['model']);

        if ($request['active'] != ""){
            $builder->where('active','=',$request['active']);
        }

        $builder->orderBy('car.model');
        return $builder->paginate(config('app.list_count'))->appends($request->except('page'));
    }

    public function save(array $options = [])
    {
        if($this->model == "")
        {
            return new Exception("O campo modelo é obrigatório.");
        }

        if($this->license_plate == "")
        {
            return new Exception("O campo placa é obrigatório.");
        }

        if ($this->color == "")
        {
            return new Exception("O campo cor é obrigatório.");
        }

        if ($this->chassis == "")
        {
            return new Exception("O campo chassi é obrigatório.");
        }

        if ($this->driver_license == "")
        {
            return new Exception("O campo CNH motorista é obrigatório.");
        }

        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public static function updateArray($id_contract, $itens)
    {
        try {
            DB::beginTransaction();
            foreach ($itens as $item) {
                $verificador = isset($item['active']) ? false : true;

                //adicionando valores
                if (empty($item['id_contract']) && $verificador === true)
                {
                    if (empty($item['id_contract']))
                        $item['id_contract'] = $id_contract;

                    $item = new Car($item);
                    $item['id_contract'] = $id_contract;
                    $item->save();
                }
                //excluindo valores
                else if (!empty($item['id_contract'])&& $verificador === false)
                {
                    Car::query()
                        ->where('id_contract', '=', $id_contract)
                        ->where('id', '=', $item['id'])->delete();

                }

            }

            DB::commit();
            return true;

        }catch (\Exception $e){
            DB::rollBack();
            return $e;
        }
    }

    public static function getSelect(){
        return Car::where('active','=',1)->get();
    }
}