<?php

namespace App\Models;

use App\Models\Helpers\CawModel;
use App\Models\Helpers\CawHelpers;
use Illuminate\Http\Request;
use \DB;
use Mockery\Exception;

class History extends CawModel
{

    protected $table    =  'history';
    protected $fillable = [
        'id_person',
        'description',
        'contact_time',
        'contact_time_hour'
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];

    public $timestamps = true;

    public static function getList(Request $request){

        $builder = History::select('history.*', 'person.name_social_name')
                            ->join('person', 'person.id', '=', 'history.id_person');


        CawHelpers::addWhereLike($builder, 'name_social_name', $request['name_social_name']);
        if ($request['bigger_than'])
        {
            $builder->where('contact_time','>=',$request['bigger_than']);
        }

        if ($request['less_than'])
        {
            $builder->where('contact_time','<=',$request['less_than']);
        }

        $builder->orderBy('person.name_social_name');

        return $builder->paginate(config('app.list_count'))->appends($request->except('page'));
    }

    public function save(array $options = [])
    {
        if ($this->responsible != auth()->user()->id && $this->id != ""){
            return new Exception("Você não foi o criador deste histórico e por isso não pode editá-lo!");
        }
        if($this->id_person == "")
        {
            return new Exception("O campo nome é obrigatório.");
        }

        if($this->contact_time == "")
        {
            return new Exception("O campo data é obrigatório.");
        }

        if($this->description == "")
        {
            return new Exception("O campo descrição é obrigatório.");
        }

        return parent::save($options); // TODO: Change the autogenerated stub
    }


    public function getCreatedAtAttribute($value)
    {
        if ($value != "")
        {
            $value = CawHelpers::decodeData($value, true);
        }

        return $value;
    }
    public static function getSelect(){
        return History::where('active','=',1)->get();
    }
}