<?php

namespace App\Models;

use App\Models\Helpers\CawModel;
use App\Models\Helpers\CawHelpers;
use Illuminate\Http\Request;
use \DB;

class History extends CawModel
{

    protected $table    =  'history';
    protected $fillable = [
        'id_person',
        'description',
        'contact_time',
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];

    public $timestamps = true;

    public static function getList(Request $request){

        $builder = History::select('history.*', 'person.name_social_name')
                            ->join('person', 'person.id', '=', 'history.id_person');

        CawHelpers::addWhereLike($builder, 'name_social_name', $request['name_social_name']);

        $builder->orderBy('person.name_social_name');

        return $builder->paginate(config('app.list_count'))->appends($request->except('page'));
    }

    public function save(array $options = [])
    {
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function getContactTimeAttribute($value)
    {
        if ($value != "")
        {
            $value = CawHelpers::decodeData($value, true);
        }

        return $value;
    }

    public function getCreatedAtAttribute($value)
    {
        if ($value != "")
        {
            $value = CawHelpers::decodeData($value, true);
        }

        return $value;
    }
}