<?php

namespace App\Models;

use App\Models\Helpers\CawModel;
use App\Models\Helpers\CawHelpers;
use Illuminate\Http\Request;
use \DB;
use Mockery\Exception;

class PaymentType extends CawModel
{

    protected $table    =  'payment_type';
    protected $fillable = [
        'name',
        'type',
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];

    public $timestamps = true;

    public static function getList(Request $request){

        $builder = PaymentType::select('payment_type.*');

        CawHelpers::addWhereLike($builder, 'name', $request['name']);
        CawHelpers::addWhereLike($builder, 'type', $request['type']);

        if( $request['active'] != null){
            $builder->where('active', '=',  $request['active']);
        }

        $builder->orderBy('payment_type.name');

        return $builder->paginate(config('app.list_count'))->appends($request->except('page'));
    }

    public function save(array $options = [])
    {
        if($this->name == "")
        {
            return new Exception("O campo nome é obrigatório.");
        }

        if($this->type == "")
        {
            return new Exception("O campo tipo de pagamento é obrigatório.");
        }




        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function getContactTimeAttribute($value)
    {
        if ($value != "")
        {
            $value = CawHelpers::decodeData($value, true);
        }

        return $value;
    }

    public function getCreatedAtAttribute($value)
    {
        if ($value != "")
        {
            $value = CawHelpers::decodeData($value, true);
        }

        return $value;
    }

    public static function activeDisabled($id, $type){

        try {
            $payment_type = PaymentType::where('id', '=', $id)
                ->first();
            if($payment_type != null) {

                if ($type == 1) {
                    $payment_type->active = 0;
                } else {
                    $payment_type->active = 1;
                }

                $res = $payment_type->save();

                if($res === true){
                    return true;
                }else{
                    return false;
                }
            }else{
                return false;
            }

        }catch (QueryException $e){
            return false;
        }
    }

    public static function getSelect(){
        return PaymentType::where('active','=',1)->get();
    }

    public static function selectAll(){
        return PaymentType::groupBy('name','type')->orderBy('name')->get();
    }
}