<?php

namespace App\Models;

use App\Models\Helpers\CawModel;

class UserGrupo extends CawModel
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table    =  'user_grupo';
    protected $fillable = [
        'nome',
        'data_cad',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];
    public $timestamps = false;

    public function getUserGrupoPermissoes(){
        return $this->hasMany(UserGrupoPermissao::class, 'id_user_grupo')->pluck('id_permissao');
    }

    public function setUserGrupoPermissoes($permissoes){
        try{
            $res = UserGrupoPermissao::where('id_user_grupo', '=', $this->id)->delete();
            if($res === false){
                return false;
            }

            foreach ($permissoes as $item){
                $res = (new UserGrupoPermissao(['id_user_grupo' => $this->id, 'id_permissao' => $item]))->save();
                if($res === false){
                    return false;
                }
            }
        }catch (QueryException $e){
            return $e;
        }
        return true;
    }

    public function save(array $options = [])
    {
        if(empty($this->id)) {
            $this->data_cad = date('Y-m-d H:i:s');
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }


}